name: "simple CI"

on:
  push:
    branches:
      - "master"

jobs:
  build-test-deploy:
    name: Build, test and deploy on github page
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/checkout@v2

      - name: "Install dependency"
        run: npm ci

      - name: "Build"
        run: npm run build

      - name: "Test"
        run: npm test

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: github-pages-build
          folder: build
